/**
 * Example Pages Function handler.
 *
 * This file was auto-generated by flaregun to demonstrate the available bindings.
 * Modify or replace it with your own handler implementation.
 */

interface Env {
  DB: D1Database;
}

export const onRequest: PagesFunction<Env> = async ({ env }) => {
  // Example D1 database query
  // const result = await env.DB.prepare('SELECT * FROM users').all();

  return new Response("Hello from flaregun!", {
    headers: { "Content-Type": "text/plain" },
  });
};
