import { describe, test, expect } from "bun:test";
import { mkdtempSync, writeFileSync, readFileSync, rmSync } from "fs";
import { join } from "path";
import { tmpdir } from "os";
import {
  loadLockFile,
  saveLockFile,
  lookupResource,
  storeResource,
  removeService,
  clearState,
  emptyState,
  LockFileParseError,
} from "../src/lock/index.js";
import type { LockState } from "../src/lock/index.js";

// --- Test Helpers ---

/** Creates a temporary directory for test files. Returns the path. */
function makeTmpDir(): string {
  return mkdtempSync(join(tmpdir(), "flaregun-lock-test-"));
}

/** Builds a fully populated lock state for testing. */
function fullState(): LockState {
  return {
    tunnel: { id: "tunnel-uuid-123" },
    pages: {
      photos: {
        project_name: "my-photos",
        d1_database_id: "d1-uuid-456",
        r2_bucket_name: "photos-bucket",
        kv_namespace_id: "kv-uuid-789",
      },
      blog: {
        project_name: "my-blog",
      },
    },
    access: {
      photos: { app_id: "access-app-photos" },
      api: { app_id: "access-app-api" },
    },
    worker: { name: "fallback-worker" },
  };
}

// --- Loading Tests ---

describe("lock file loading", () => {
  test("loading a lock file that does not exist returns empty state without error", () => {
    const tmpDir = makeTmpDir();
    try {
      const state = loadLockFile(join(tmpDir, "flaregun.lock"));
      expect(state.tunnel).toBeUndefined();
      expect(state.pages).toEqual({});
      expect(state.access).toEqual({});
      expect(state.worker).toBeUndefined();
    } finally {
      rmSync(tmpDir, { recursive: true, force: true });
    }
  });

  test("loading a valid lock file returns all tracked resource IDs correctly", () => {
    const tmpDir = makeTmpDir();
    const lockPath = join(tmpDir, "flaregun.lock");

    const yaml = `
tunnel:
  id: tunnel-uuid-123
pages:
  photos:
    project_name: my-photos
    d1_database_id: d1-uuid-456
    r2_bucket_name: photos-bucket
    kv_namespace_id: kv-uuid-789
  blog:
    project_name: my-blog
access:
  photos:
    app_id: access-app-photos
  api:
    app_id: access-app-api
worker:
  name: fallback-worker
`;
    writeFileSync(lockPath, yaml);

    try {
      const state = loadLockFile(lockPath);

      expect(state.tunnel).toEqual({ id: "tunnel-uuid-123" });
      expect(state.pages.photos.project_name).toBe("my-photos");
      expect(state.pages.photos.d1_database_id).toBe("d1-uuid-456");
      expect(state.pages.photos.r2_bucket_name).toBe("photos-bucket");
      expect(state.pages.photos.kv_namespace_id).toBe("kv-uuid-789");
      expect(state.pages.blog.project_name).toBe("my-blog");
      expect(state.access.photos.app_id).toBe("access-app-photos");
      expect(state.access.api.app_id).toBe("access-app-api");
      expect(state.worker).toEqual({ name: "fallback-worker" });
    } finally {
      rmSync(tmpDir, { recursive: true, force: true });
    }
  });

  test("loading a lock file with invalid YAML produces a parse error", () => {
    const tmpDir = makeTmpDir();
    const lockPath = join(tmpDir, "flaregun.lock");
    writeFileSync(lockPath, "tunnel:\n  id: [broken yaml\n");

    try {
      expect(() => loadLockFile(lockPath)).toThrow(LockFileParseError);
    } finally {
      rmSync(tmpDir, { recursive: true, force: true });
    }
  });

  test("loading a lock file with non-object root produces a parse error", () => {
    const tmpDir = makeTmpDir();
    const lockPath = join(tmpDir, "flaregun.lock");
    writeFileSync(lockPath, "- just a list\n- of items\n");

    try {
      expect(() => loadLockFile(lockPath)).toThrow(LockFileParseError);
    } finally {
      rmSync(tmpDir, { recursive: true, force: true });
    }
  });

  test("loading an empty lock file returns empty state", () => {
    const tmpDir = makeTmpDir();
    const lockPath = join(tmpDir, "flaregun.lock");
    writeFileSync(lockPath, "");

    try {
      const state = loadLockFile(lockPath);
      expect(state.pages).toEqual({});
      expect(state.access).toEqual({});
    } finally {
      rmSync(tmpDir, { recursive: true, force: true });
    }
  });
});

// --- Saving Tests ---

describe("lock file saving", () => {
  test("saving a lock file writes valid YAML to disk", () => {
    const tmpDir = makeTmpDir();
    const lockPath = join(tmpDir, "flaregun.lock");

    try {
      const state = fullState();
      saveLockFile(lockPath, state);

      const content = readFileSync(lockPath, "utf-8");
      // Should contain the auto-generated header
      expect(content).toContain("Auto-generated by flaregun");
      expect(content).toContain("do not edit manually");

      // Should contain resource IDs
      expect(content).toContain("tunnel-uuid-123");
      expect(content).toContain("my-photos");
      expect(content).toContain("d1-uuid-456");
    } finally {
      rmSync(tmpDir, { recursive: true, force: true });
    }
  });

  test("roundtrip: save and re-load produces identical state", () => {
    const tmpDir = makeTmpDir();
    const lockPath = join(tmpDir, "flaregun.lock");

    try {
      const original = fullState();
      saveLockFile(lockPath, original);
      const loaded = loadLockFile(lockPath);

      expect(loaded.tunnel).toEqual(original.tunnel);
      expect(loaded.pages).toEqual(original.pages);
      expect(loaded.access).toEqual(original.access);
      expect(loaded.worker).toEqual(original.worker);
    } finally {
      rmSync(tmpDir, { recursive: true, force: true });
    }
  });

  test("roundtrip with empty state produces empty state on reload", () => {
    const tmpDir = makeTmpDir();
    const lockPath = join(tmpDir, "flaregun.lock");

    try {
      const original = emptyState();
      saveLockFile(lockPath, original);
      const loaded = loadLockFile(lockPath);

      expect(loaded.tunnel).toBeUndefined();
      expect(loaded.pages).toEqual({});
      expect(loaded.access).toEqual({});
      expect(loaded.worker).toBeUndefined();
    } finally {
      rmSync(tmpDir, { recursive: true, force: true });
    }
  });

  test("saved lock file never contains environment variable values or secrets", () => {
    const tmpDir = makeTmpDir();
    const lockPath = join(tmpDir, "flaregun.lock");

    try {
      const state = fullState();
      saveLockFile(lockPath, state);

      const content = readFileSync(lockPath, "utf-8");

      // Should NOT contain any env-var-like patterns or known secret strings
      expect(content).not.toContain("CLOUDFLARE_API_TOKEN");
      expect(content).not.toContain("CLOUDFLARE_ACCOUNT_ID");
      expect(content).not.toContain("CLOUDFLARE_ZONE_ID");
      expect(content).not.toContain("CLOUDFLARE_TUNNEL_TOKEN");
      expect(content).not.toContain("apiToken");
      expect(content).not.toContain("api_token");

      // Should only contain resource IDs and structural keys
      expect(content).toContain("tunnel");
      expect(content).toContain("pages");
      expect(content).toContain("access");
      expect(content).toContain("worker");
    } finally {
      rmSync(tmpDir, { recursive: true, force: true });
    }
  });
});

// --- Lookup Tests ---

describe("lock file lookup", () => {
  test("looking up a resource ID for an existing service returns the correct ID", () => {
    const state = fullState();

    expect(lookupResource(state, "photos", "pages_project")).toBe("my-photos");
    expect(lookupResource(state, "photos", "d1_database")).toBe("d1-uuid-456");
    expect(lookupResource(state, "photos", "r2_bucket")).toBe("photos-bucket");
    expect(lookupResource(state, "photos", "kv_namespace")).toBe("kv-uuid-789");
    expect(lookupResource(state, "photos", "access_app")).toBe(
      "access-app-photos",
    );
    expect(lookupResource(state, "api", "access_app")).toBe("access-app-api");
  });

  test("looking up a resource ID for a non-existent service returns undefined", () => {
    const state = fullState();

    expect(lookupResource(state, "nonexistent", "pages_project")).toBeUndefined();
    expect(lookupResource(state, "nonexistent", "d1_database")).toBeUndefined();
    expect(lookupResource(state, "nonexistent", "r2_bucket")).toBeUndefined();
    expect(lookupResource(state, "nonexistent", "kv_namespace")).toBeUndefined();
    expect(lookupResource(state, "nonexistent", "access_app")).toBeUndefined();
  });

  test("looking up optional resource that is not set returns undefined", () => {
    const state = fullState();
    // blog has a pages project but no D1/R2/KV
    expect(lookupResource(state, "blog", "pages_project")).toBe("my-blog");
    expect(lookupResource(state, "blog", "d1_database")).toBeUndefined();
    expect(lookupResource(state, "blog", "r2_bucket")).toBeUndefined();
    expect(lookupResource(state, "blog", "kv_namespace")).toBeUndefined();
  });
});

// --- Store Tests ---

describe("lock file store", () => {
  test("storing a new resource ID updates the in-memory state", () => {
    const state = emptyState();

    storeResource(state, "newapp", "pages_project", "new-project-name");
    expect(state.pages.newapp.project_name).toBe("new-project-name");
  });

  test("storing a D1 database ID on an existing pages entry updates it", () => {
    const state = fullState();

    storeResource(state, "blog", "d1_database", "new-d1-id");
    expect(state.pages.blog.d1_database_id).toBe("new-d1-id");
    // Existing project_name should be preserved
    expect(state.pages.blog.project_name).toBe("my-blog");
  });

  test("storing an access app ID updates the access section", () => {
    const state = emptyState();

    storeResource(state, "myservice", "access_app", "access-id-123");
    expect(state.access.myservice.app_id).toBe("access-id-123");
  });

  test("storing a resource ID for a service without existing pages entry creates it", () => {
    const state = emptyState();

    storeResource(state, "newapp", "d1_database", "d1-new-id");
    expect(state.pages.newapp).toBeDefined();
    expect(state.pages.newapp.d1_database_id).toBe("d1-new-id");
  });

  test("storing R2 and KV on existing pages entries updates them", () => {
    const state = fullState();

    storeResource(state, "blog", "r2_bucket", "blog-bucket");
    storeResource(state, "blog", "kv_namespace", "blog-kv-ns");
    expect(state.pages.blog.r2_bucket_name).toBe("blog-bucket");
    expect(state.pages.blog.kv_namespace_id).toBe("blog-kv-ns");
    expect(state.pages.blog.project_name).toBe("my-blog");
  });
});

// --- Remove Tests ---

describe("lock file remove", () => {
  test("removing entries for a service clears all that service's resource IDs", () => {
    const state = fullState();

    // photos has pages (with D1, R2, KV) and access entries
    removeService(state, "photos");

    expect(state.pages.photos).toBeUndefined();
    expect(state.access.photos).toBeUndefined();

    // Other services should be unaffected
    expect(state.pages.blog.project_name).toBe("my-blog");
    expect(state.access.api.app_id).toBe("access-app-api");
  });

  test("removing a non-existent service is a no-op (no error)", () => {
    const state = fullState();

    removeService(state, "nonexistent");

    // State should be unchanged
    expect(Object.keys(state.pages)).toHaveLength(2);
    expect(Object.keys(state.access)).toHaveLength(2);
  });
});

// --- Clear Tests ---

describe("lock file clear", () => {
  test("clearing the entire state resets to empty", () => {
    const state = fullState();

    clearState(state);

    expect(state.tunnel).toBeUndefined();
    expect(state.pages).toEqual({});
    expect(state.access).toEqual({});
    expect(state.worker).toBeUndefined();
  });
});
