/**
 * Fallback Worker source generator.
 *
 * Produces a complete, self-contained TypeScript Worker source file with
 * the domain name and down page HTML embedded as constants. The generated
 * source inlines the routing logic from `handler.ts` so the deployed Worker
 * has no external dependencies.
 *
 * The generator handles two scenarios for the down page HTML:
 * 1. **No custom down_page** — uses the built-in default template with
 *    the domain name injected
 * 2. **Custom down_page file** — reads the file and embeds its raw contents
 */

import { readFileSync, writeFileSync, existsSync } from "fs";
import { join, resolve } from "path";
import { defaultDownPageHtml } from "./down-page.js";

// --- Error Types ---

/** Thrown when a custom down_page file is specified but does not exist */
export class DownPageNotFoundError extends Error {
  constructor(public readonly filePath: string) {
    super(
      `Custom down page file not found: ${filePath}. ` +
        `Check the "down_page" path in your flaregun.yml config.`,
    );
    this.name = "DownPageNotFoundError";
  }
}

// --- Types ---

/** Options for generating the fallback Worker source */
export interface GenerateWorkerOptions {
  /** The base domain (e.g., "example.com") */
  domain: string;
  /** Optional path to a custom down page HTML file (relative to config file) */
  downPagePath?: string;
  /** Base directory for resolving relative down_page paths (defaults to cwd) */
  basePath?: string;
}

/** Result of generating the fallback Worker source */
export interface GenerateWorkerResult {
  /** The generated TypeScript source code */
  source: string;
  /** The down page HTML that was embedded */
  downPageHtml: string;
}

// --- Constants ---

/** Expected filename for the fallback Worker source (must match wrangler.toml main) */
export const WORKER_SOURCE_FILENAME = "index.ts";

// --- Generator ---

/**
 * Resolves the down page HTML content.
 *
 * If a custom path is provided, reads that file. Otherwise, generates the
 * built-in default HTML with the domain name injected.
 *
 * @param domain - The base domain for the default template
 * @param downPagePath - Optional path to a custom HTML file
 * @param basePath - Base directory for resolving relative paths
 * @returns The HTML content to embed in the Worker
 * @throws {DownPageNotFoundError} If a custom path is specified but the file doesn't exist
 */
export function resolveDownPageHtml(
  domain: string,
  downPagePath?: string,
  basePath?: string,
): string {
  if (!downPagePath) {
    return defaultDownPageHtml(domain);
  }

  const resolvedPath = resolve(basePath ?? process.cwd(), downPagePath);
  if (!existsSync(resolvedPath)) {
    throw new DownPageNotFoundError(resolvedPath);
  }

  return readFileSync(resolvedPath, "utf-8");
}

/**
 * Generates the complete TypeScript source for the deployable fallback Worker.
 *
 * The generated source is self-contained — it inlines the routing logic and
 * embeds the domain and down page HTML as string constants. The Worker exports
 * both `handleRequest` (for testability) and the default fetch handler.
 *
 * @param options - Generation options (domain, optional custom down page)
 * @returns The generated source code and embedded HTML
 * @throws {DownPageNotFoundError} If a custom down_page path is specified but doesn't exist
 */
export function generateWorkerSource(
  options: GenerateWorkerOptions,
): GenerateWorkerResult {
  const { domain, downPagePath, basePath } = options;

  const downPageHtml = resolveDownPageHtml(domain, downPagePath, basePath);

  // Escape backticks and backslashes in the HTML for safe embedding in a template literal
  const escapedHtml = downPageHtml
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");

  const source = `/**
 * Fallback Worker for ${domain}
 *
 * Auto-generated by flaregun. Do not edit manually.
 *
 * Routes all subdomain traffic with graceful offline fallback:
 * - Bare domain and www: pass through to origin
 * - down subdomain: serve the embedded offline page
 * - All other subdomains: proxy to origin, redirect to down page on failure
 */

const DOMAIN = ${JSON.stringify(domain)};
const DOWN_URL = \`https://down.\${DOMAIN}\`;

const DOWN_PAGE_HTML = \`${escapedHtml}\`;

/** Dependency-injectable fetch type for testability. */
type FetchFn = (request: Request) => Promise<Response>;

/**
 * Core request handler for the fallback Worker.
 */
export async function handleRequest(
  request: Request,
  originFetch: FetchFn = globalThis.fetch,
): Promise<Response> {
  const { hostname } = new URL(request.url);

  // Pass through bare domain — the redirect rule handles it, not us
  if (hostname === DOMAIN) {
    return originFetch(request);
  }

  // Extract subdomain (everything before .domain)
  const suffix = \`.\${DOMAIN}\`;
  if (!hostname.endsWith(suffix)) {
    // Not our domain at all — pass through (shouldn't happen with routes)
    return originFetch(request);
  }
  const subdomain = hostname.slice(0, -suffix.length);

  // Pass through www — Cloudflare Pages handles it
  if (subdomain === "www") {
    return originFetch(request);
  }

  // Serve the inline "down" page directly
  if (subdomain === "down") {
    return new Response(DOWN_PAGE_HTML, {
      status: 200,
      headers: { "Content-Type": "text/html; charset=utf-8" },
    });
  }

  // All other subdomains: try the origin (tunnel), redirect on failure
  try {
    const response = await originFetch(request);

    // 2xx, 3xx, and 4xx pass through unmodified
    if (response.status < 500) {
      return response;
    }

    // 5xx — tunnel or origin error, redirect to down page
    return Response.redirect(DOWN_URL, 302);
  } catch {
    // Network error — tunnel is unreachable
    return Response.redirect(DOWN_URL, 302);
  }
}

export default {
  async fetch(request: Request): Promise<Response> {
    return handleRequest(request);
  },
};
`;

  return { source, downPageHtml };
}

/**
 * Generates the fallback Worker source and writes it to the target directory.
 *
 * The file is written with the filename expected by the wrangler.toml entry
 * point (index.ts).
 *
 * @param targetDir - Directory to write the generated source file to
 * @param options - Generation options (domain, optional custom down page)
 * @returns Path to the written source file
 * @throws {DownPageNotFoundError} If a custom down_page path is specified but doesn't exist
 */
export function writeWorkerSource(
  targetDir: string,
  options: GenerateWorkerOptions,
): string {
  const { source } = generateWorkerSource(options);
  const filePath = join(targetDir, WORKER_SOURCE_FILENAME);
  writeFileSync(filePath, source, "utf-8");
  return filePath;
}
