import { load, dump } from "js-yaml";
import { readFileSync, writeFileSync, existsSync } from "fs";

// --- Types ---

/** Resource data tracked for a Pages service */
export interface PagesEntry {
  project_name: string;
  d1_database_id?: string;
  r2_bucket_name?: string;
  kv_namespace_id?: string;
}

/** Resource data tracked for a tunnel */
export interface TunnelEntry {
  id: string;
}

/** Resource data tracked for an Access application */
export interface AccessEntry {
  app_id: string;
}

/** Resource data tracked for the fallback Worker */
export interface WorkerEntry {
  name: string;
}

/** The full lock file state — only Cloudflare resource identifiers, never secrets */
export interface LockState {
  tunnel?: TunnelEntry;
  pages: Record<string, PagesEntry>;
  access: Record<string, AccessEntry>;
  worker?: WorkerEntry;
}

/** Resource types that can be looked up in the lock state */
export type ResourceType =
  | "pages_project"
  | "d1_database"
  | "r2_bucket"
  | "kv_namespace"
  | "access_app";

// --- Lock File Header ---

const LOCK_FILE_HEADER =
  "# Auto-generated by flaregun — do not edit manually.\n# This file tracks provisioned Cloudflare resource IDs.\n\n";

// --- Parse Error ---

export class LockFileParseError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "LockFileParseError";
  }
}

// --- Core Functions ---

/** Creates an empty lock state (first-run scenario). */
export function emptyState(): LockState {
  return {
    tunnel: undefined,
    pages: {},
    access: {},
    worker: undefined,
  };
}

/**
 * Loads the lock file from the given path.
 * - If the file does not exist, returns an empty state (no error).
 * - If the file exists but contains invalid YAML, throws a LockFileParseError.
 */
export function loadLockFile(filePath: string): LockState {
  if (!existsSync(filePath)) {
    return emptyState();
  }

  const content = readFileSync(filePath, "utf-8");

  let parsed: unknown;
  try {
    parsed = load(content);
  } catch (err) {
    throw new LockFileParseError(
      `Failed to parse lock file at ${filePath}: ${err instanceof Error ? err.message : String(err)}`,
    );
  }

  // Empty file or YAML that parses to null/undefined
  if (parsed == null) {
    return emptyState();
  }

  if (typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new LockFileParseError(
      `Lock file at ${filePath} must be a YAML object, got ${Array.isArray(parsed) ? "array" : typeof parsed}`,
    );
  }

  const obj = parsed as Record<string, unknown>;

  const state = emptyState();

  // Parse tunnel section
  if (obj.tunnel && typeof obj.tunnel === "object") {
    const tunnel = obj.tunnel as Record<string, unknown>;
    if (typeof tunnel.id === "string") {
      state.tunnel = { id: tunnel.id };
    }
  }

  // Parse pages section
  if (obj.pages && typeof obj.pages === "object" && !Array.isArray(obj.pages)) {
    const pages = obj.pages as Record<string, unknown>;
    for (const [name, entry] of Object.entries(pages)) {
      if (entry && typeof entry === "object" && !Array.isArray(entry)) {
        const e = entry as Record<string, unknown>;
        if (typeof e.project_name === "string") {
          const pagesEntry: PagesEntry = { project_name: e.project_name };
          if (typeof e.d1_database_id === "string") {
            pagesEntry.d1_database_id = e.d1_database_id;
          }
          if (typeof e.r2_bucket_name === "string") {
            pagesEntry.r2_bucket_name = e.r2_bucket_name;
          }
          if (typeof e.kv_namespace_id === "string") {
            pagesEntry.kv_namespace_id = e.kv_namespace_id;
          }
          state.pages[name] = pagesEntry;
        }
      }
    }
  }

  // Parse access section
  if (
    obj.access &&
    typeof obj.access === "object" &&
    !Array.isArray(obj.access)
  ) {
    const access = obj.access as Record<string, unknown>;
    for (const [name, entry] of Object.entries(access)) {
      if (entry && typeof entry === "object" && !Array.isArray(entry)) {
        const e = entry as Record<string, unknown>;
        if (typeof e.app_id === "string") {
          state.access[name] = { app_id: e.app_id };
        }
      }
    }
  }

  // Parse worker section
  if (obj.worker && typeof obj.worker === "object") {
    const worker = obj.worker as Record<string, unknown>;
    if (typeof worker.name === "string") {
      state.worker = { name: worker.name };
    }
  }

  return state;
}

/**
 * Saves the lock state to disk as YAML with a header comment.
 * The output file includes a header indicating it is auto-generated.
 */
export function saveLockFile(filePath: string, state: LockState): void {
  // Build a clean serializable object (omit undefined top-level keys)
  const obj: Record<string, unknown> = {};

  if (state.tunnel) {
    obj.tunnel = state.tunnel;
  }

  // Only include pages and access when non-empty to keep output clean
  if (Object.keys(state.pages).length > 0) {
    obj.pages = state.pages;
  }

  if (Object.keys(state.access).length > 0) {
    obj.access = state.access;
  }

  if (state.worker) {
    obj.worker = state.worker;
  }

  const yaml = dump(obj, { lineWidth: -1, noRefs: true });
  writeFileSync(filePath, LOCK_FILE_HEADER + yaml, "utf-8");
}

/**
 * Looks up a resource ID for a given service and resource type.
 * Returns the resource identifier string if found, or undefined if not found.
 */
export function lookupResource(
  state: LockState,
  serviceName: string,
  resourceType: ResourceType,
): string | undefined {
  switch (resourceType) {
    case "pages_project": {
      const entry = state.pages[serviceName];
      return entry?.project_name;
    }
    case "d1_database": {
      const entry = state.pages[serviceName];
      return entry?.d1_database_id;
    }
    case "r2_bucket": {
      const entry = state.pages[serviceName];
      return entry?.r2_bucket_name;
    }
    case "kv_namespace": {
      const entry = state.pages[serviceName];
      return entry?.kv_namespace_id;
    }
    case "access_app": {
      const entry = state.access[serviceName];
      return entry?.app_id;
    }
  }
}

/**
 * Stores a resource identifier in the in-memory state.
 * The caller is responsible for calling saveLockFile afterwards.
 */
export function storeResource(
  state: LockState,
  serviceName: string,
  resourceType: ResourceType,
  resourceId: string,
): void {
  switch (resourceType) {
    case "pages_project": {
      if (!state.pages[serviceName]) {
        state.pages[serviceName] = { project_name: resourceId };
      } else {
        state.pages[serviceName].project_name = resourceId;
      }
      break;
    }
    case "d1_database": {
      if (!state.pages[serviceName]) {
        state.pages[serviceName] = {
          project_name: "",
          d1_database_id: resourceId,
        };
      } else {
        state.pages[serviceName].d1_database_id = resourceId;
      }
      break;
    }
    case "r2_bucket": {
      if (!state.pages[serviceName]) {
        state.pages[serviceName] = {
          project_name: "",
          r2_bucket_name: resourceId,
        };
      } else {
        state.pages[serviceName].r2_bucket_name = resourceId;
      }
      break;
    }
    case "kv_namespace": {
      if (!state.pages[serviceName]) {
        state.pages[serviceName] = {
          project_name: "",
          kv_namespace_id: resourceId,
        };
      } else {
        state.pages[serviceName].kv_namespace_id = resourceId;
      }
      break;
    }
    case "access_app": {
      state.access[serviceName] = { app_id: resourceId };
      break;
    }
  }
}

/**
 * Removes all entries for a given service from the lock state.
 * Clears Pages project data (including D1, R2, KV) and Access app entries.
 */
export function removeService(state: LockState, serviceName: string): void {
  delete state.pages[serviceName];
  delete state.access[serviceName];
}

/**
 * Resets the entire lock state to empty.
 * Used by the destroy command after all resources are deleted.
 */
export function clearState(state: LockState): void {
  state.tunnel = undefined;
  state.pages = {};
  state.access = {};
  state.worker = undefined;
}
