/**
 * Functions scaffolder for Pages services.
 *
 * Creates a starter `functions/` directory for Pages services that declare
 * cloud resources (D1 database, R2 bucket, KV namespace) but don't yet have
 * a functions directory. This is a one-time operation — if the target directory
 * already exists, the scaffolder does nothing.
 *
 * The scaffolded directory contains:
 * - An example API handler demonstrating usage of the declared bindings
 * - A tsconfig.json referencing @cloudflare/workers-types for editor support
 */

import { existsSync, mkdirSync, writeFileSync } from "fs";
import { resolve } from "path";
import type { ServiceConfig } from "../config/index.js";

// --- Types ---

/** Result of a scaffold operation */
export interface ScaffoldResult {
  /** Whether scaffolding actually created files, or was skipped */
  action: "scaffolded" | "skipped";
  /** The target directory path */
  path: string;
}

// --- Scaffolder ---

/**
 * Scaffolds a starter functions directory for a Pages service.
 *
 * Creates an example handler file and a tsconfig.json in the target directory.
 * If the directory already exists, does nothing and returns "skipped".
 *
 * @param service - The service configuration (needs cloud resource flags and functions path)
 * @param projectRoot - The root directory of the service's project (used to resolve relative paths)
 * @returns Result indicating whether scaffolding occurred or was skipped
 */
export function scaffoldFunctions(
  service: ServiceConfig,
  projectRoot: string,
): ScaffoldResult {
  // Determine the target functions directory path (resolve normalizes trailing slashes)
  const functionsPath = resolve(
    projectRoot,
    service.functions ?? "functions",
  );

  // Guard: never overwrite an existing directory
  if (existsSync(functionsPath)) {
    return { action: "skipped", path: functionsPath };
  }

  // Create the directory
  mkdirSync(functionsPath, { recursive: true });

  // Generate and write the example handler
  const handlerContent = generateExampleHandler(service);
  writeFileSync(resolve(functionsPath, "api.ts"), handlerContent, "utf-8");

  // Generate and write the tsconfig
  const tsconfigContent = generateTsconfig();
  writeFileSync(
    resolve(functionsPath, "tsconfig.json"),
    tsconfigContent,
    "utf-8",
  );

  return { action: "scaffolded", path: functionsPath };
}

// --- Content Generators ---

/**
 * Generates the content of the example handler file.
 *
 * The handler demonstrates usage of whichever bindings the service declares.
 * If no cloud resources are declared, it produces a minimal handler.
 */
function generateExampleHandler(service: ServiceConfig): string {
  const hasDb = service.database === true;
  const hasBucket = service.bucket === true;
  const hasKv = service.kv === true;

  // Build the Env interface fields
  const envFields: string[] = [];
  if (hasDb) envFields.push("  DB: D1Database;");
  if (hasBucket) envFields.push("  BUCKET: R2Bucket;");
  if (hasKv) envFields.push("  KV: KVNamespace;");

  // Build the handler body lines
  const bodyLines: string[] = [];

  if (hasDb) {
    bodyLines.push(
      "  // Example D1 database query",
      "  // const result = await env.DB.prepare('SELECT * FROM users').all();",
    );
  }

  if (hasBucket) {
    bodyLines.push(
      "  // Example R2 bucket operation",
      "  // const object = await env.BUCKET.get('example-key');",
    );
  }

  if (hasKv) {
    bodyLines.push(
      "  // Example KV namespace operation",
      "  // const value = await env.KV.get('example-key');",
    );
  }

  // Build the full file content
  const lines: string[] = [];
  lines.push("/**");
  lines.push(" * Example Pages Function handler.");
  lines.push(" *");
  lines.push(
    " * This file was auto-generated by flaregun to demonstrate the available bindings.",
  );
  lines.push(
    " * Modify or replace it with your own handler implementation.",
  );
  lines.push(" */");
  lines.push("");

  // Env interface (only if there are bindings)
  if (envFields.length > 0) {
    lines.push("interface Env {");
    lines.push(...envFields);
    lines.push("}");
    lines.push("");
    lines.push(
      "export const onRequest: PagesFunction<Env> = async ({ env }) => {",
    );
  } else {
    lines.push("export const onRequest: PagesFunction = async () => {");
  }

  if (bodyLines.length > 0) {
    lines.push(...bodyLines);
    lines.push("");
  }

  lines.push('  return new Response("Hello from flaregun!", {');
  lines.push("    headers: { \"Content-Type\": \"text/plain\" },");
  lines.push("  });");
  lines.push("};");
  lines.push("");

  return lines.join("\n");
}

/**
 * Generates the content of the tsconfig.json file for the functions directory.
 *
 * References @cloudflare/workers-types so that binding types (D1Database,
 * R2Bucket, KVNamespace, PagesFunction) are available in the user's editor.
 */
function generateTsconfig(): string {
  const tsconfig = {
    compilerOptions: {
      target: "ESNext",
      module: "ESNext",
      moduleResolution: "bundler",
      strict: true,
      types: ["@cloudflare/workers-types"],
    },
  };
  return JSON.stringify(tsconfig, null, 2) + "\n";
}
